name: "Progressive Koalition"
description: '#ProKo statt GroKo'
post_path: "/news/:slug/"


source: "."
dest: "./_site"
sass:
  style: Compressed

ignore:
  - "README.md"
  - "LICENSE"
  - "bootstrap-4.0.0-beta.3"
